#!/bin/bash

if ! git diff --quiet HEAD
then
  echo "There are uncommited changes. Abort..."
  exit 1
fi

make CXXFLAGS="-DGRAPH_REPR -DTREE_REPR" GDB=off eval.exe || exit 1

if [ -z $OMP_NUM_THREADS ]
then
  export OMP_NUM_THREADS=12
fi

echo -n 'Question prompting the experiment: '
RATIONALE=$(head -n 1 | awk '{print "# " $0}')

JOB_ID=$(env TS_ONFINISH=./run_after ts -E -N $OMP_NUM_THREADS ./eval.exe $@)

FILE=output/ts.$JOB_ID.txt

echo "Results: $FILE"

echo "$RATIONALE
# 
# Commit: $(git rev-parse HEAD)" > $FILE

