#!/bin/bash

if [ -z $OMP_NUM_THREADS ]
then
  export OMP_NUM_THREADS=12
fi

echo -n 'Question prompting the experiment: '
RATIONALE=$(head -n 1 | awk '{print "# " $0}')

JOB_ID=$(env TS_ONFINISH=./run_after ts -E -N $OMP_NUM_THREADS ./eval.exe $@)

FILE=output/ts_$JOB_ID.txt

echo "$RATIONALE
# 
# Commit: $(git rev-parse HEAD)" > $FILE

echo "Results: output/ts_$JOB_ID.txt"

